### **Libraries import**

In [1]:
import pandas as pd

### **Pandas read file**

In [2]:
df = pd.read_csv("global_fuel_prices_2020_2026.csv")

In [3]:
df.head()

,date,country,region,income_level,subsidy_level,petrol_usd_liter,diesel_usd_liter,lpg_usd_liter,brent_crude_usd,tax_percentage
0,2020-01-06,United States,North America,High,Low,1.465,1.289,1.093,65.75,59.6
1,2020-01-13,United States,North America,High,Low,1.435,1.319,1.077,65.54,27.6
2,2020-01-20,United States,North America,High,Low,1.446,1.329,1.080,66.51,62.3
3,2020-01-27,United States,North America,High,Low,1.488,1.359,1.125,68.79,44.8
4,2020-02-03,United States,North America,High,Low,1.457,1.341,1.111,68.44,51.4

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 27468 entries, 0 to 27467
Data columns (total 10 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   date              27468 non-null  object
 1   country           27468 non-null  object
 2   region            27468 non-null  object
 3   income_level      27468 non-null  object
 4   subsidy_level     27468 non-null  object
 5   petrol_usd_liter  27468 non-null  float64
 6   diesel_usd_liter  27468 non-null  float64
 7   lpg_usd_liter     27468 non-null  float64
 8   brent_crude_usd   27468 non-null  float64
 9   tax_percentage    27468 non-null  float64
dtypes: float64(5), object(5)
memory usage: 2.1+ MB

In [5]:
df.describe()

,petrol_usd_liter,diesel_usd_liter,lpg_usd_liter,brent_crude_usd,tax_percentage
count,27468.000000,27468.000000,27468.000000,27468.000000,27468.000000
mean,2.281915,2.133760,1.711473,106.686453,26.774468
std,1.540612,1.465058,1.155543,18.972391,17.203349
min,0.010000,0.010000,0.010000,47.970000,0.000000
25%,0.926000,0.858000,0.695000,101.140000,13.500000
50%,2.116500,1.954500,1.588000,112.270000,23.400000
75%,3.457000,3.231000,2.590000,119.410000,38.900000
max,6.779000,6.240000,5.100000,130.000000,65.000000

### **Datatype check**

In [6]:
df.dtypes

date                 object
country              object
region               object
income_level         object
subsidy_level        object
petrol_usd_liter    float64
diesel_usd_liter    float64
lpg_usd_liter       float64
brent_crude_usd     float64
tax_percentage      float64
dtype: object

### **Date column standardization**

In [7]:
pd.to_datetime(df['date'])

0       2020-01-06
1       2020-01-13
2       2020-01-20
3       2020-01-27
4       2020-02-03
           ...
27463   2026-03-09
27464   2026-03-16
27465   2026-03-23
27466   2026-03-30
27467   2026-04-06
Name: date, Length: 27468, dtype: datetime64[ns]

### **Check for missing value**

In [8]:
df.isnull().sum()

date                0
country             0
region              0
income_level        0
subsidy_level       0
petrol_usd_liter    0
diesel_usd_liter    0
lpg_usd_liter       0
brent_crude_usd     0
tax_percentage      0
dtype: int64

### **Check for duplicate**

In [9]:
df.duplicated().sum()

np.int64(0)

### **Assign numeric values to income_level**

In [10]:
income_map = {'Low':1, 'Middle':2, 'High':3}
df['income_num'] = df['income_level'].map(income_map)

### **Assign numeric values to subsidy_level**

In [11]:
subsidy_map = {'Low':1, 'Medium':2, 'High':3, 'Very High':4}
df['subsidy_num'] = df['subsidy_level'].map(subsidy_map)

### **Number of Countries**

In [12]:
number_of_countries = df['country'].nunique()

print("Number of Countries:", number_of_countries)

Number of Countries: 84

In [13]:
kpi_countries = pd.DataFrame({
    'KPI': ['Number of Countries'],
    'Value': [df['country'].nunique()]})

kpi_countries.to_csv('number_of_countries.csv', index=False)

### **Number of Regions**

In [14]:
number_of_regions = df['region'].nunique()

print("Number of Regions:", number_of_regions)

Number of Regions: 7

In [15]:
kpi_regions = pd.DataFrame({
    'KPI': ['Number of Regions'],
    'Value': [df['region'].nunique()]})

kpi_regions.to_csv('number_of_regions.csv', index=False)

### **Q1: Average Fuel Prices by Countries**

**Countries with Highest Average Fuel Prices**

In [16]:
country_avg = (df.groupby('country', as_index=False)
      .agg(avg_petrol=('petrol_usd_liter', 'mean'),
          avg_diesel=('diesel_usd_liter', 'mean'),
          avg_lpg=('lpg_usd_liter', 'mean')))

country_avg['avg_fuel_price'] = country_avg[['avg_petrol', 'avg_diesel', 'avg_lpg']].mean(axis=1)

highest_countries = country_avg.sort_values('avg_fuel_price', ascending=False).head(10)

print(highest_countries)

        country  avg_petrol  avg_diesel   avg_lpg  avg_fuel_price
24    Hong Kong    5.540618    5.097009  4.155303        4.930977
50       Norway    4.764419    4.431119  3.573336        4.256292
30      Ireland    4.653841    4.545272  3.489859        4.229657
47  Netherlands    4.655067    4.322697  3.490407        4.156057
15      Denmark    4.543031    4.320624  3.406196        4.089950
62    Singapore    4.542700    4.210722  3.407009        4.053477
68       Sweden    4.431144    4.099755  3.323581        3.951493
69  Switzerland    4.386908    4.165627  3.291226        3.947920
6       Belgium    4.320615    4.210089  3.239728        3.923477
19      Finland    4.255153    4.165422  3.192278        3.870951

**Countries and Average Highest Fuel Price only**

In [17]:
country_avg['avg_fuel_price'] = country_avg[['avg_petrol', 'avg_diesel', 'avg_lpg']].mean(axis=1)
highest_countries = country_avg[['country', 'avg_fuel_price']].sort_values('avg_fuel_price', ascending=False).head(10)

print(highest_countries)

        country  avg_fuel_price
24    Hong Kong        4.930977
50       Norway        4.256292
30      Ireland        4.229657
47  Netherlands        4.156057
15      Denmark        4.089950
62    Singapore        4.053477
68       Sweden        3.951493
69  Switzerland        3.947920
6       Belgium        3.923477
19      Finland        3.870951

In [18]:
highest_countries.to_csv('highest_countries.csv', index=False)

**Countries with Lowest Average Fuel Prices**

In [19]:
country_avg = (df.groupby('country', as_index=False)
      .agg(avg_petrol=('petrol_usd_liter', 'mean'),
          avg_diesel=('diesel_usd_liter', 'mean'),
          avg_lpg=('lpg_usd_liter', 'mean')))

country_avg['avg_fuel_price'] = country_avg[['avg_petrol', 'avg_diesel', 'avg_lpg']].mean(axis=1)

lowest_countries = country_avg.sort_values('avg_fuel_price').head(10)

print(lowest_countries)

         country  avg_petrol  avg_diesel   avg_lpg  avg_fuel_price
80     Venezuela    0.015584    0.017437  0.016254        0.016425
28          Iran    0.039853    0.033000  0.031098        0.034650
39         Libya    0.056382    0.048661  0.042284        0.049109
0        Algeria    0.140517    0.118092  0.105905        0.121505
29          Iraq    0.164098    0.142177  0.122159        0.142811
17         Egypt    0.171792    0.163306  0.128807        0.154635
37        Kuwait    0.194104    0.176621  0.145199        0.171975
49       Nigeria    0.213156    0.192780  0.160859        0.188932
56         Qatar    0.232581    0.210153  0.175061        0.205932
60  Saudi Arabia    0.249758    0.221456  0.187443        0.219552

**Countries and Average Lowest Fuel Price only**

In [20]:
country_avg['avg_fuel_price'] = country_avg[['avg_petrol', 'avg_diesel', 'avg_lpg']].mean(axis=1)
lowest_countries = country_avg[['country', 'avg_fuel_price']].sort_values('avg_fuel_price').head(10)

print(lowest_countries)

         country  avg_fuel_price
80     Venezuela        0.016425
28          Iran        0.034650
39         Libya        0.049109
0        Algeria        0.121505
29          Iraq        0.142811
17         Egypt        0.154635
37        Kuwait        0.171975
49       Nigeria        0.188932
56         Qatar        0.205932
60  Saudi Arabia        0.219552

In [21]:
lowest_countries.to_csv('lowest_countries.csv', index=False)

### **Q2: Average Tax Percentage by Countries**

**Countries with the highest average tax percentage on fuel**

In [22]:
highest_tax_countries = (df.groupby('country', as_index=False)
      .agg(avg_tax_percentage=('tax_percentage', 'mean'))
      .sort_values('avg_tax_percentage', ascending=False))

print("Countries with the highest average tax percentage on fuel")
print(highest_tax_countries.head(10))

Countries with the highest average tax percentage on fuel
           country  avg_tax_percentage
59          Rwanda           39.563914
48     New Zealand           39.273394
21         Germany           39.213150
74          Turkey           38.991131
15         Denmark           38.865443
78  United Kingdom           38.781040
30         Ireland           38.714985
14  Czech Republic           38.614067
70          Taiwan           38.332416
43      Mozambique           38.272783

In [23]:
highest_tax_countries.to_csv('highest_tax_countries.csv', index=False)

**Countries with the lowest average tax percentage on fuel**

In [24]:
lowest_tax_countries = (df.groupby('country', as_index=False)
      .agg(avg_tax_percentage=('tax_percentage', 'mean'))
      .sort_values('avg_tax_percentage'))

print("Countries with the lowest average tax percentage on fuel")
print(lowest_tax_countries.head(10))

Countries with the lowest average tax percentage on fuel
        country  avg_tax_percentage
28         Iran           13.899694
42      Morocco           13.906116
56        Qatar           13.937920
5    Bangladesh           14.269113
49      Nigeria           14.303058
33  Ivory Coast           14.590214
77      Ukraine           14.606728
61      Senegal           14.612232
2     Argentina           14.616208
41       Mexico           14.652905

In [25]:
lowest_tax_countries.to_csv('lowest_tax_countries.csv', index=False)

### **Q3: Average Fuel Price by Region**

In [26]:
region_avg = (df.groupby('region', as_index=False)
      .agg(avg_petrol_price=('petrol_usd_liter', 'mean'),
          avg_diesel_price=('diesel_usd_liter', 'mean'),
          avg_lpg_price=('lpg_usd_liter', 'mean')))

region_avg['avg_fuel_price'] = region_avg[['avg_petrol_price', 'avg_diesel_price', 'avg_lpg_price']].mean(axis=1)

region_avg = region_avg.sort_values('region')

print(region_avg)

          region  avg_petrol_price  avg_diesel_price  avg_lpg_price  \
0         Africa          1.549482          1.426697       1.162121
1           Asia          2.140571          1.976584       1.605441
2         Europe          3.701695          3.517597       2.776193
3    Middle East          1.225935          1.141471       0.919475
4  North America          2.064176          1.892420       1.548336
5        Oceania          3.655203          3.466560       2.742182
6  South America          1.425393          1.290224       1.069333

   avg_fuel_price
0        1.379433
1        1.907532
2        3.331828
3        1.095627
4        1.834978
5        3.287982
6        1.261650

**Regions and average fuel price**

In [27]:
region_avg = (df.groupby('region', as_index=False)
      .agg(avg_petrol=('petrol_usd_liter', 'mean'),
          avg_diesel=('diesel_usd_liter', 'mean'),
          avg_lpg=('lpg_usd_liter', 'mean')))

region_avg['avg_fuel_price'] = region_avg[['avg_petrol', 'avg_diesel', 'avg_lpg']].mean(axis=1)

region_avg = region_avg[['region', 'avg_fuel_price']].sort_values('region')

print(region_avg)

          region  avg_fuel_price
0         Africa        1.379433
1           Asia        1.907532
2         Europe        3.331828
3    Middle East        1.095627
4  North America        1.834978
5        Oceania        3.287982
6  South America        1.261650

In [28]:
region_avg[['region', 'avg_fuel_price']].to_csv('region_avg.csv', index=False)

### **Q4: Low-Income Countries' Affordability Analysis for Different Subsidy Categories.**

In [31]:
df['afford_index'] = df['petrol_usd_liter'] / df['income_num']

subsidy_effect = df[df['income_num']==1].groupby('subsidy_num')['afford_index'].mean()
print("Low income affordability by subsidy level:\n", subsidy_effect.sort_index())

Low income affordability by subsidy level:
 subsidy_num
1    2.347654
2    1.449440
3    0.640187
4    0.114229
Name: afford_index, dtype: float64

In [32]:
low_income_countries = df[df['income_num'] == 1][['country', 'region', 'subsidy_num', 'afford_index']]

for subsidy in [1, 2, 3, 4]:
    top5 = (low_income_countries[low_income_countries['subsidy_num'] == subsidy]
        .groupby('country', as_index=False)['afford_index']
        .mean()
        .sort_values('afford_index', ascending=False)
        .head(5)
        .reset_index(drop=True))
    
    print(f"\nLow-income countries affordability by subsidy_num={subsidy}:")
    print(top5)
    
    top5.to_csv(f'top5_low_income_subsidy_{subsidy}.csv', index=False)

Low-income countries affordability by subsidy_num=1:
      country  afford_index
0    Zimbabwe      2.584242
1      Rwanda      2.498569
2      Zambia      2.497673
3  Mozambique      2.412584
4      Uganda      2.327927

Low-income countries affordability by subsidy_num=2:
       country  afford_index
0        Nepal      1.612144
1    Sri Lanka      1.545749
2      Senegal      1.477924
3     Ethiopia      1.413000
4  Ivory Coast      1.408933

Low-income countries affordability by subsidy_num=3:
    country  afford_index
0   Myanmar      0.756963
1  Pakistan      0.713480
2     Sudan      0.568431
3    Angola      0.521872

Low-income countries affordability by subsidy_num=4:
     country  afford_index
0    Nigeria      0.213156
1      Egypt      0.171792
2      Libya      0.056382
3  Venezuela      0.015584

### **Q5: Average Subsidy by Region**

In [33]:
region_subsidy = (df.groupby('region', as_index=False)
      .agg(avg_subsidy=('subsidy_num', 'mean'))
      .sort_values('avg_subsidy', ascending=False)
      .head(10))

print("Regions with the highest average subsidy")
print(region_subsidy)

Regions with the highest average subsidy
          region  avg_subsidy
3    Middle East     3.000000
6  South America     2.428571
0         Africa     2.000000
1           Asia     1.882353
4  North America     1.666667
2         Europe     1.173913
5        Oceania     1.000000

In [34]:
region_subsidy.to_csv('region_subsidy.csv', index=False)

### **Q6: Average Tax Percentage on Fuel by Regions**

In [35]:
tax_by_region = (df.groupby('region', as_index=False)
      .agg(avg_tax_percentage=('tax_percentage', 'mean'))
      .sort_values('avg_tax_percentage', ascending=False))

print(tax_by_region)

          region  avg_tax_percentage
5        Oceania           38.687003
2         Europe           34.606914
4  North America           29.208053
0         Africa           25.785068
1           Asia           23.014049
3    Middle East           19.598981
6  South America           18.201704

In [36]:
tax_by_region.to_csv('tax_by_region.csv', index=False)

### **Q7: Average Fuel Prices by Year**

In [38]:
df['date'] = pd.to_datetime(df['date'], errors='coerce')

df['avg_fuel_price'] = df[['petrol_usd_liter', 'diesel_usd_liter', 'lpg_usd_liter']].mean(axis=1)

yearly_fuel_summary = (df.groupby(df['date'].dt.year)
      .agg(avg_petrol_price=('petrol_usd_liter', 'mean'),
          avg_diesel_price=('diesel_usd_liter', 'mean'),
          avg_lpg_price=('lpg_usd_liter', 'mean'),
          avg_fuel_price=('avg_fuel_price', 'mean'))
      .reset_index()
      .rename(columns={'date': 'year'})
      .sort_values('year'))

print(yearly_fuel_summary)

   year  avg_petrol_price  avg_diesel_price  avg_lpg_price  avg_fuel_price
0  2020          1.484851          1.389316       1.113647        1.329271
1  2021          2.279826          2.131215       1.710005        2.040349
2  2022          2.505177          2.342340       1.878884        2.242134
3  2023          2.233670          2.089211       1.675400        1.999427
4  2024          2.545121          2.379906       1.908957        2.277995
5  2025          2.539506          2.374147       1.904502        2.272718
6  2026          2.646955          2.474332       1.985003        2.368764

**Year and average fuel price**

In [39]:
yearly_fuel_summary = (df.groupby(df['date'].dt.year)
      .agg(avg_fuel_price=('avg_fuel_price', 'mean'))
        
      .reset_index()
      .rename(columns={'date': 'year'})
      .sort_values('year'))

print(yearly_fuel_summary)

   year  avg_fuel_price
0  2020        1.329271
1  2021        2.040349
2  2022        2.242134
3  2023        1.999427
4  2024        2.277995
5  2025        2.272718
6  2026        2.368764

In [40]:
yearly_fuel_summary[['year', 'avg_fuel_price']].to_csv('yearly_fuel.csv', index=False)

### **Q8: Regional Income Level Analysis**

In [41]:
df['income_level'] = df['income_level'].astype(str).str.strip()

counts = df.groupby(['region', 'income_level']).size().reset_index(name='count')

region_totals = counts.groupby('region')['count'].sum().reset_index(name='region_total')

counts = counts.merge(region_totals, on='region')
counts['share_pct'] = (counts['count'] / counts['region_total']) * 100

order = ['Low','Middle','High']
spread = counts.pivot(index='region', columns='income_level', values='share_pct').reindex(columns=order).fillna(0)

region_summary = region_totals.merge(spread.reset_index(), on='region')

region_summary = region_summary.sort_values(by='region', ascending=True).reset_index(drop=True)

print(region_summary)

          region  region_total        Low     Middle        High
0         Africa          7521  73.913043  26.086957    0.000000
1           Asia          5559  29.411765  41.176471   29.411765
2         Europe          7521   0.000000  26.086957   73.913043
3    Middle East          2943   0.000000  44.444444   55.555556
4  North America           981   0.000000  33.333333   66.666667
5        Oceania           654   0.000000   0.000000  100.000000
6  South America          2289  14.285714  71.428571   14.285714

In [42]:
region_summary.drop(columns=['region_total']).to_csv('region_income_spread.csv', index=False)

### **Q9: Regional Subsidy Level Analysis**

In [43]:
df['subsidy_level'] = df['subsidy_level'].astype(str).str.strip()

counts = df.groupby(['region','subsidy_level']).size().reset_index(name='count')

region_totals = counts.groupby('region')['count'].sum().reset_index(name='region_total')

counts = counts.merge(region_totals, on='region')
counts['share_pct'] = (counts['count'] / counts['region_total']) * 100

order = ['Low','Medium','High','Very High']
spread = counts.pivot(index='region', columns='subsidy_level', values='share_pct').reindex(columns=order).fillna(0)

region_summary = region_totals.merge(spread.reset_index(), on='region')

sort_col = 'Very High'
region_summary = region_summary.sort_values(by=sort_col, ascending=False).reset_index(drop=True)

print(region_summary)

          region  region_total         Low     Medium       High  Very High
0    Middle East          2943   22.222222  11.111111  11.111111  55.555556
1         Africa          7521   47.826087  21.739130  13.043478  17.391304
2  South America          2289   14.285714  42.857143  28.571429  14.285714
3         Europe          7521   86.956522   8.695652   4.347826   0.000000
4           Asia          5559   35.294118  41.176471  23.529412   0.000000
5  North America           981   66.666667   0.000000  33.333333   0.000000
6        Oceania           654  100.000000   0.000000   0.000000   0.000000

In [44]:
region_summary.drop(columns=['region_total']).to_csv('region_subsidy_spread.csv', index=False)